### ISSUE TITLE
Feature | `MischiefOptions.captureVideoAsAttachment`: Capture of principal video and associated meta data as attachment

### ISSUE THREAD

**Issue by matteocargnelutti** [harvard-lil/scoop#17]
> 🚧  Work in progress

Out-of-browser capture step for principal video using `yt-dlp`. 
Resulting files attached to archive as `file:///video-extracted.mp4` and `file:///video-extracted-metadata.json`, presented in `pages.jsonl` as alternative entry point.

## To think-through
- [x] Should we use `youtube-dl-exec` or spawn `yt-dlp` directly?
  - Replaced by direct spawning 
- [x] Solidify pipeline for downloading `yt-dlp` _(versioning, provenance)_ 
  - Replaced by direct pull from specific GitHub release
- [x] Look into hanging processes at the end of capture
  - No longer a problem with direct spawning
- [x] Exclusion list _(only run step on certain domains / url patterns?)_
  - Managed with error handling 
- [x] Document system-level `python 3` dependency
- [x] What should we do if there's more than one video on a given page?
- [x] Can we also get the subtitles?
- [x] Should we generate a summary HTML page combining the resulting video and meta data captured in the process?
